http://localhost:8000/todos

###
http://localhost:8000/todos/0c5c2d08-1c89-42c2-abd8-14424fd26658

###
POST http://localhost:8000/todos
content-type: application/json

{
    "title": "Title 3",
    "content": "Content 3",
    "done": false
}

###
PUT http://localhost:8000/todos
content-type: application/json

{
    "id": "f2feec39-0cc5-4946-a55d-17fe8b71b6cb"
}

###
DELETE  http://localhost:8000/todos
content-type: application/json

{
    "id": "0c228ccb-67d7-4d72-8eae-7e96e07820ca"
}
